--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 20 2024 13:25
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Branch'   The Branch entity represents the bank branches where customers can access banking services.
-- BranchID        :  
-- BranchName      :  
-- BranchAddress   :  
-- BranchPhoneNumber :  
--
CREATE TABLE Branch (
    BranchID       NUMBER(38) NOT NULL,
    BranchName     VARCHAR2(20) NOT NULL,
    BranchAddress  VARCHAR2(20) NOT NULL,
    BranchPhoneNumber NUMBER NOT NULL,
CONSTRAINT pk_Branch PRIMARY KEY (BranchID))
/


--
-- Create Table    : 'Customer'   The Customer entity represents the bank's customers who hold accounts with the bank.
-- CustomerID      :  
-- FirstName       :  
-- LastName        :  
-- DateOfBirth     :  
-- Address         :  
-- ContactNumber   :  
-- Email           :  
--
CREATE TABLE Customer (
    CustomerID     NUMBER(38) NOT NULL,
    FirstName      VARCHAR2(20) NOT NULL,
    LastName       VARCHAR2(20) NOT NULL,
    DateOfBirth    DATE NOT NULL,
    Address        VARCHAR2(20) NOT NULL,
    ContactNumber  NUMBER NOT NULL,
    Email          VARCHAR2(40) NOT NULL,
CONSTRAINT pk_Customer PRIMARY KEY (CustomerID))
/


--
-- Create Table    : 'Account'   The Account entity represents the bank accounts held by customers.
-- AccountID       :  
-- Balance         :  
-- DateOpened      :  
-- AccountStatus   :  
-- BranchID        :  (references Branch.BranchID)
--
CREATE TABLE Account (
    AccountID      NUMBER(38) NOT NULL,
    Balance        NUMBER NOT NULL,
    DateOpened     DATE NOT NULL,
    AccountStatus  VARCHAR2(20) NOT NULL,
    BranchID       NUMBER(38),
CONSTRAINT pk_Account PRIMARY KEY (AccountID),
CONSTRAINT fk_Account FOREIGN KEY (BranchID)
    REFERENCES Branch (BranchID))
/


--
-- Create Table    : 'Vip'   The Vip entity represents VIP customers who have special privileges and benefits.
-- AccountID       :  (references Account.AccountID)
-- PositiveInterest :  
--
CREATE TABLE Vip (
    AccountID      NUMBER(38) NOT NULL,
    PositiveInterest FLOAT NOT NULL,
CONSTRAINT pk_Vip PRIMARY KEY (AccountID),
CONSTRAINT fk_Vip FOREIGN KEY (AccountID)
    REFERENCES Account (AccountID))
/


--
-- Create Table    : 'BlackList'   The BlackList entity represents customers who have been blacklisted due to certain reasons.
-- AccountID       :  (references Account.AccountID)
-- NegetiveInterest :  
-- MinimumMinus    :  
--
CREATE TABLE BlackList (
    AccountID      NUMBER(38) NOT NULL,
    NegetiveInterest FLOAT NOT NULL,
    MinimumMinus   NUMBER NOT NULL,
CONSTRAINT pk_BlackList PRIMARY KEY (AccountID),
CONSTRAINT fk_BlackList FOREIGN KEY (AccountID)
    REFERENCES Account (AccountID))
/


--
-- Create Table    : 'Rel5'   
-- CustomerID      :  (references Customer.CustomerID)
-- AccountID       :  (references Account.AccountID)
--
CREATE TABLE Rel5 (
    CustomerID     NUMBER(38) NOT NULL,
    AccountID      NUMBER(38) NOT NULL,
CONSTRAINT pk_Rel5 PRIMARY KEY (CustomerID,AccountID),
CONSTRAINT fk_Rel5 FOREIGN KEY (CustomerID)
    REFERENCES Customer (CustomerID)
    ON DELETE CASCADE,
CONSTRAINT fk_Rel52 FOREIGN KEY (AccountID)
    REFERENCES Account (AccountID))
/


--
-- Create Table    : 'DirectDebit'   The DirectDebit entity represents the direct debit arrangements set up by customers for recurring payments.
-- IDDebit         :  
-- StartDate       :  
-- TypeDebit       :  
-- Amount          :  
-- IDAccount       :  
-- IDBranch        :  
-- AccountID       :  (references Account.AccountID)
--
CREATE TABLE DirectDebit (
    IDDebit        NUMBER(38) NOT NULL,
    StartDate      DATE NOT NULL,
    TypeDebit      VARCHAR2(20) NOT NULL,
    Amount         NUMBER NOT NULL,
    IDAccount      NUMBER(38) NOT NULL,
    IDBranch       NUMBER(38) NOT NULL,
    AccountID      NUMBER(38),
CONSTRAINT pk_DirectDebit PRIMARY KEY (IDDebit),
CONSTRAINT fk_DirectDebit FOREIGN KEY (AccountID)
    REFERENCES Account (AccountID))
/


--
-- Create Table    : 'Transactions'   The Transaction entity represents the transactions associated with customer accounts.
-- TransactionID   :  
-- AccountID       :  
-- TransactionType :  
-- Amount          :  
-- TransactionDate :  
-- AccountID1      :  (references Account.AccountID)
--
CREATE TABLE Transactions (
    TransactionID  NUMBER(38) NOT NULL,
    AccountID      NUMBER(38) NOT NULL,
    TransactionType VARCHAR2(20) NOT NULL,
    Amount         NUMBER NOT NULL,
    TransactionDate DATE NOT NULL,
    AccountID1     NUMBER(38),
CONSTRAINT pk_Transactions PRIMARY KEY (TransactionID),
CONSTRAINT fk_Transactions FOREIGN KEY (AccountID1)
    REFERENCES Account (AccountID))
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Branch TO public
/
GRANT ALL ON Customer TO public
/
GRANT ALL ON Account TO public
/
GRANT ALL ON Vip TO public
/
GRANT ALL ON BlackList TO public
/
GRANT ALL ON Rel5 TO public
/
GRANT ALL ON DirectDebit TO public
/
GRANT ALL ON Transactions TO public
/


